export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCSES = "FETCH_BOOKS_SUCCSES";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
export const INCREASE_ITEMS_IN_CART = "INCREASE_ITEMS_IN_CART";
export const DECREASE_ITEMS_IN_CART = "DECREASE_ITEMS_IN_CART";
export const DELETE_ITEMS_FROM_CART = "DELETE_ITEMS_FROM_CART";
